const fs = require('node:fs');
const path = require('node:path');
const childProcess = require('node:child_process');

const VERSION = '2.0.0';

const MODES = {
  mentored: 'Mentored',
  vibe: 'Vibe'
};

const TOOLS = {
  'claude-code': 'Claude Code',
  'codex-cli': 'OpenAI Codex CLI',
  'claude-chat': 'Claude.ai / Pro',
  chatgpt: 'ChatGPT / GPT-4o',
  cursor: 'Cursor',
  windsurf: 'Windsurf',
  generic: 'Other'
};

const PROJECT_TYPES = {
  web: 'web',
  systems: 'systems',
  creative: 'creative'
};

const TOOL_ENTRY = {
  'claude-code': 'CLAUDE.md',
  'codex-cli': 'AGENTS.md',
  'claude-chat': 'LIKIT_CONTEXT.md',
  chatgpt: 'LIKIT_GPT.md',
  cursor: '.cursor/rules/likit.mdc',
  windsurf: '.windsurfrules',
  generic: 'LIKIT_PROMPT.md'
};

const TOOL_START = {
  'claude-code': 'Open Claude Code in this directory: claude',
  'codex-cli': 'Open Codex in this directory: codex',
  'claude-chat': 'Copy LIKIT_CONTEXT.md and paste it at the start of a new Claude chat',
  chatgpt: 'Copy LIKIT_GPT.md and paste it at the start of a new ChatGPT chat',
  cursor: '.cursor/rules/likit.mdc has been created. Open Cursor in this directory.',
  windsurf: '.windsurfrules has been created. Open Windsurf in this directory.',
  generic: 'Copy LIKIT_PROMPT.md and paste it at the start of any AI chat'
};

const PROTECTED_USER_FILES = new Set(['Progress.md', 'ProjectSummary.md']);

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function writeJson(file, value) {
  fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`);
}

function readConfig(cwd) {
  const configPath = path.join(cwd, '.likit', 'config.json');
  if (!fs.existsSync(configPath)) {
    throw new Error('No .likit/config.json found. Run: npx likit init');
  }
  return readJson(configPath);
}

function tryReadConfig(cwd) {
  try {
    return readConfig(cwd);
  } catch (_error) {
    return null;
  }
}

function templateRoot() {
  return path.resolve(__dirname, '..', 'templates');
}

function templateDir(options) {
  return path.join(templateRoot(), options.mode, options.tool);
}

function isValidChoice(value, map) {
  return Object.prototype.hasOwnProperty.call(map, value);
}

function assertOptions(options) {
  if (!isValidChoice(options.mode, MODES)) {
    throw new Error(`Invalid mode: ${options.mode}`);
  }
  if (!isValidChoice(options.tool, TOOLS)) {
    throw new Error(`Invalid tool: ${options.tool}`);
  }
  if (!isValidChoice(options.projectType, PROJECT_TYPES)) {
    throw new Error(`Invalid project type: ${options.projectType}`);
  }
}

function listTemplateFiles(dir) {
  if (!fs.existsSync(dir)) {
    throw new Error(`Template directory missing: ${dir}`);
  }

  const results = [];
  const stack = [dir];
  while (stack.length > 0) {
    const current = stack.pop();
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
      } else if (entry.isFile()) {
        results.push(path.relative(dir, full));
      }
    }
  }
  return results.sort();
}

function destinationFor(tool, relativeFile) {
  const file = relativeFile.replaceAll(path.sep, '/');
  if (tool === 'cursor' && file === 'likit.mdc') {
    return path.join('.cursor', 'rules', 'likit.mdc');
  }
  if (tool === 'windsurf' && file === 'likit.windsurfrules') {
    return '.windsurfrules';
  }
  return file;
}

function slugify(value) {
  return String(value || 'developer')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'developer';
}

function gitUsername(cwd) {
  try {
    const output = childProcess.execSync('git config user.name', {
      cwd,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    }).trim();
    return output ? slugify(output) : null;
  } catch (_error) {
    return null;
  }
}

function progressFooter(options) {
  return [
    '',
    '---',
    `Generated by Likit v${VERSION} \u00b7 Mode: ${MODES[options.mode]} \u00b7 Tool: ${TOOLS[options.tool]} \u00b7 Type: ${options.projectType}`,
    ''
  ].join('\n');
}

function appendProgressFooter(file, options) {
  if (!fs.existsSync(file)) return;
  const content = fs.readFileSync(file, 'utf8');
  if (content.includes('Generated by Likit v')) return;
  fs.writeFileSync(file, `${content.trimEnd()}${progressFooter(options)}`);
}

function writeGitignore(cwd, dryRun, generatedFiles) {
  const file = path.join(cwd, '.gitignore');
  const relative = '.gitignore';
  let content = '';

  if (fs.existsSync(file)) {
    content = fs.readFileSync(file, 'utf8');
  }

  const hasEnv = content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .some((line) => line === '.env');

  if (hasEnv) return;

  generatedFiles.push(relative);
  if (dryRun) return;

  const addition = '# Likit: secrets should never be in the repo (H8)\n.env\n';
  fs.writeFileSync(file, content.trim() ? `${content.trimEnd()}\n\n${addition}` : addition);
}

// Codex loads no slash commands, so its quick reference lists plain-language
// requests instead of /commands. Every other supported tool reads /commands.
const SLASH_COMMANDS = [
  '- `/phase-check`      - where am I, what is next',
  '- `/phase-status`     - live phase, remaining steps, overall progress',
  '- `/progress-log`     - full progress report',
  '- `/progress-save`    - save current progress',
  '- `/phase-explain`    - explain this phase in depth',
  '- `/step-explain`     - explain this checkpoint in depth',
  '- `/gate-rollback`    - undo the last gate advance',
  '- `/mode-status`      - show mode and tool config',
  '- `/session-bundle`   - regenerate paste context',
  '- `/likit-help`       - show all commands',
  '- `/export-template`  - save this project as a reusable template',
  '- `/likit-start`      - populate planning files from prompt.md'
].join('\n');

const SPOKEN_COMMANDS = [
  '- "show phase status"  - live phase, remaining steps, overall progress',
  '- "explain this phase" / "explain this step"',
  '- "save progress" / "full progress report"',
  '- "roll back the last gate"',
  '- "show mode" / "config"',
  '- "regenerate the session bundle"',
  '- "list commands"',
  '- "export template"',
  '- "read prompt.md and populate the planning files"'
].join('\n');

function howToUse(options) {
  const mode = MODES[options.mode];
  const type = options.projectType;
  const codex = options.tool === 'codex-cli';
  const commandsHeading = codex
    ? '## Requests (ask in plain language — Codex does not load slash commands)'
    : '## Commands';
  const commonCommands = codex ? SPOKEN_COMMANDS : SLASH_COMMANDS;

  const starts = {
    'claude-code': 'Run `claude` in this directory. Claude reads `CLAUDE.md` automatically.',
    'codex-cli': 'Run `codex` in this directory. Codex reads `AGENTS.md` project instructions automatically.',
    'claude-chat': 'Open Claude.ai, paste `LIKIT_CONTEXT.md` at the start of a new chat, then continue from the current gate.',
    chatgpt: 'Open ChatGPT, paste `LIKIT_GPT.md` at the start of a new chat, then continue from the current gate. ChatGPT Plus users can also upload the generated files individually.',
    cursor: 'Open Cursor in this directory. The rule file is `.cursor/rules/likit.mdc`.',
    windsurf: 'Open Windsurf in this directory. The rule file is `.windsurfrules`.',
    generic: 'Paste `LIKIT_PROMPT.md` at the start of a new chat with any AI assistant.'
  };

  return `# Likit Quick Reference - ${TOOLS[options.tool]}

${starts[options.tool]}

${commandsHeading}
${commonCommands}

## Terminal
- \`npx likit start\`            - populate planning files from prompt.md
- \`npx likit sync\`             - update Likit templates, not user content
- \`npx likit doctor\`           - validate setup
- \`npx likit session-bundle\`   - regenerate paste context
- \`npx likit export-template\`  - export G0 output
- \`npx likit import-template\`  - import a .likit.json template

## Mode: ${mode} \u00b7 Project: ${type}
`;
}

function generatedConfig(options, cwd) {
  const teamMode = Boolean(options.teamMode);
  const username = teamMode ? (options.username || gitUsername(cwd) || 'developer') : null;
  return {
    version: VERSION,
    created: new Date().toISOString(),
    mode: options.mode,
    tool: options.tool,
    projectType: options.projectType,
    teamMode,
    username: username ? slugify(username) : null
  };
}

function dryRunFileList(options, cwd) {
  assertOptions(options);
  const source = templateDir(options);
  const files = listTemplateFiles(source).map((file) => destinationFor(options.tool, file));
  files.push(path.join('.likit', 'config.json'));
  files.push(path.join('.likit', 'HOW_TO_USE.md'));
  if (options.teamMode) {
    const username = slugify(options.username || gitUsername(cwd) || 'developer');
    files.push(path.join('.likit', `Progress_${username}.md`));
  }
  const gitignore = path.join(cwd, '.gitignore');
  if (!fs.existsSync(gitignore)) {
    files.push('.gitignore');
  } else {
    const content = fs.readFileSync(gitignore, 'utf8');
    const hasEnv = content
      .split(/\r?\n/)
      .map((line) => line.trim())
      .some((line) => line === '.env');
    if (!hasEnv) files.push('.gitignore');
  }
  return Array.from(new Set(files)).sort();
}

function generateFiles(options) {
  const cwd = options.cwd || process.cwd();
  assertOptions(options);

  const source = templateDir(options);
  const templateFiles = listTemplateFiles(source);
  const generatedFiles = [];

  if (options.dryRun) {
    console.log('[likit] Dry run file list:');
    for (const file of dryRunFileList(options, cwd)) {
      console.log(`- ${file}`);
    }
    console.log('[DRY RUN] No files written.');
    return { generatedFiles: dryRunFileList(options, cwd) };
  }

  for (const relativeFile of templateFiles) {
    const destRelative = destinationFor(options.tool, relativeFile);
    if (
      options.preserveUserContent
      && PROTECTED_USER_FILES.has(path.basename(destRelative))
      && fs.existsSync(path.join(cwd, destRelative))
    ) {
      continue;
    }
    const sourceFile = path.join(source, relativeFile);
    const destFile = path.join(cwd, destRelative);
    ensureDir(path.dirname(destFile));
    fs.copyFileSync(sourceFile, destFile);
    generatedFiles.push(destRelative);
    console.log(`\u2713 ${destRelative}`);
  }

  const likitDir = path.join(cwd, '.likit');
  ensureDir(likitDir);
  const config = generatedConfig(options, cwd);
  writeJson(path.join(likitDir, 'config.json'), config);
  generatedFiles.push(path.join('.likit', 'config.json'));
  console.log('\u2713 .likit/config.json');

  fs.writeFileSync(path.join(likitDir, 'HOW_TO_USE.md'), howToUse(config));
  generatedFiles.push(path.join('.likit', 'HOW_TO_USE.md'));
  console.log('\u2713 .likit/HOW_TO_USE.md');

  if (config.teamMode) {
    const progressTemplate = path.join(source, 'Progress.md');
    const progressContent = fs.existsSync(progressTemplate)
      ? fs.readFileSync(progressTemplate, 'utf8')
      : '# Progress\n\n**Current Gate:** G0\n';
    const personalProgress = path.join(likitDir, `Progress_${config.username}.md`);
    fs.writeFileSync(personalProgress, `${progressContent.trimEnd()}${progressFooter(config)}`);
    generatedFiles.push(path.join('.likit', `Progress_${config.username}.md`));
    console.log(`\u2713 .likit/Progress_${config.username}.md`);

    const rootProgress = [
      '# Progress',
      '',
      'Team mode - see `.likit/` for per-developer progress.',
      '',
      `Current shared setup: ${MODES[config.mode]} \u00b7 ${TOOLS[config.tool]} \u00b7 ${config.projectType}`,
      progressFooter(config).trimEnd(),
      ''
    ].join('\n');
    fs.writeFileSync(path.join(cwd, 'Progress.md'), rootProgress);
  } else {
    appendProgressFooter(path.join(cwd, 'Progress.md'), config);
  }

  writeGitignore(cwd, false, generatedFiles);

  console.log(TOOL_START[config.tool]);
  return { config, generatedFiles };
}

function printHelp() {
  console.log(`Likit v${VERSION}

Commands:
  likit                  Run setup wizard
  likit init             Run setup wizard
  likit init --dry-run   Show files that would be created
  likit start            Populate planning files from prompt.md
  likit sync             Update Likit templates, preserving user content
  likit doctor           Validate current setup
  likit migrate          Migrate old likit-claude or likit-codex setup
  likit export-template  Export G0 output to project.likit.json
  likit import-template  Import a .likit.json project template
  likit session-bundle   Regenerate paste-ready chat context
  likit team-status      Summarize team progress files
  likit version          Print version and config summary
  likit help             Show this help
`);
}

function printVersion({ cwd }) {
  const config = tryReadConfig(cwd);
  console.log(`likit ${VERSION}`);
  if (config) {
    console.log(`mode=${config.mode} tool=${config.tool} projectType=${config.projectType} teamMode=${config.teamMode}`);
  } else {
    console.log('No .likit/config.json found.');
  }
}

function teamStatus({ cwd }) {
  const config = readConfig(cwd);
  if (!config.teamMode) {
    console.log('[likit] Team mode is not enabled for this project.');
    return;
  }

  const likitDir = path.join(cwd, '.likit');
  const files = fs.existsSync(likitDir)
    ? fs.readdirSync(likitDir).filter((file) => /^Progress_.+\.md$/.test(file))
    : [];

  if (files.length === 0) {
    console.log('[likit] No per-developer progress files found.');
    return;
  }

  console.log('Developer\tCurrent Gate\tCompleted Items');
  for (const file of files.sort()) {
    const content = fs.readFileSync(path.join(likitDir, file), 'utf8');
    const gateMatch = content.match(/\*\*Current Gate:\*\*\s*(.+)/);
    const done = (content.match(/- \[x\]/g) || []).length;
    const name = file.replace(/^Progress_/, '').replace(/\.md$/, '');
    console.log(`${name}\t${gateMatch ? gateMatch[1].trim() : 'unknown'}\t${done}`);
  }
}

module.exports = {
  VERSION,
  MODES,
  TOOLS,
  PROJECT_TYPES,
  TOOL_ENTRY,
  TOOL_START,
  appendProgressFooter,
  destinationFor,
  dryRunFileList,
  generateFiles,
  gitUsername,
  howToUse,
  printHelp,
  printVersion,
  readConfig,
  slugify,
  teamStatus,
  templateDir,
  tryReadConfig,
  writeJson
};
